# Generated by Django 5.1.2 on 2025-12-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Cloudinary URL')),
                ('secure_url', models.URLField(help_text='Secure Cloudinary URL')),
                ('public_id', models.CharField(help_text='Cloudinary public ID', max_length=500)),
                ('folder', models.CharField(blank=True, help_text='Cloudinary folder', max_length=200)),
                ('filename', models.CharField(blank=True, help_text='Original filename', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text="Internal name for the section (e.g., 'hero_background', 'about_image')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown in dashboard', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Image URL', null=True)),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for the image', max_length=200)),
                ('icon_url', models.URLField(blank=True, help_text='Icon URL (if applicable)', null=True)),
                ('background_image_url', models.URLField(blank=True, help_text='Background image URL (if applicable)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Image',
                'verbose_name_plural': 'Section Images',
                'ordering': ['display_name'],
            },
        ),
    ]
