# Generated by Django 5.1.2 on 2025-12-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(help_text='Card number (1, 2, or 3)', unique=True)),
                ('title', models.CharField(help_text='Service card title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Service card subtitle', max_length=300)),
                ('image_url', models.URLField(blank=True, help_text='Card image URL', null=True)),
                ('image_alt', models.CharField(blank=True, help_text='Image alt text', max_length=200)),
                ('features', models.TextField(help_text='Features list (one per line)')),
                ('result_text', models.CharField(help_text='Result text', max_length=300)),
                ('cta_text', models.CharField(default='Learn More', help_text='Call to action text', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', help_text='Call to action link', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Management That Fits Your Goals.', max_length=200)),
                ('description', models.TextField(default='Every landlord is different. Some want complete freedom. Others prefer involvement. We tailor our service to fit you.')),
                ('cta_text', models.CharField(default='Find Your Fit', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
    ]
