# Generated by Django 5.1.2 on 2025-12-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_servicecard_servicessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='I Built This Because I Was You', max_length=200)),
                ('content', models.TextField(help_text='Main content paragraphs (one per line)')),
                ('quote_text', models.CharField(default="I don't lock clients in. I earn their trust, one transparent decision at a time.", max_length=300)),
                ('quote_author', models.CharField(default='— Mahrukh Tariq', max_length=100)),
                ('cta_text', models.CharField(default="See If We're a Fit", max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='CredibilityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(help_text='Card number (1, 2, 3, or 4)', unique=True)),
                ('title', models.CharField(help_text='Card title', max_length=200)),
                ('description', models.TextField(help_text='Card description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credibility Card',
                'verbose_name_plural': 'Credibility Cards',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='CredibilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Proven Experience. Personal Commitment.<br>Real Results.', max_length=300)),
                ('description', models.TextField(default="Garden Gate is not a franchise or volume-driven agency. It's a boutique property management firm built on 13 years of hands-on real estate experience — backed by a personal portfolio that proves its systems deliver results.")),
                ('subtitle', models.CharField(default='Why Landlords Choose Garden Gate', max_length=200)),
                ('subtitle_description', models.TextField(default="Most property managers have never been landlords. Mahrukh Tariq is both. Here's why that matters to your bottom line:")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credibility Section',
                'verbose_name_plural': 'Credibility Section',
            },
        ),
        migrations.CreateModel(
            name='FinalCTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Stop Settling. Start Succeeding.', max_length=200)),
                ('description', models.TextField(default='While others chase unresponsive managers and inflated repair bills, you can work with someone who treats your property like her own.')),
                ('cta_text', models.CharField(default='Show Me How This Actually Works', max_length=100)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final CTA Section',
                'verbose_name_plural': 'Final CTA Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Stop Losing Money to Property Managers Who Don't Care.", max_length=300)),
                ('subtitle', models.CharField(default="Your Investment Deserves an Owner's Standard.", max_length=200)),
                ('description', models.TextField(default="Most property management firms treat you like another number. At Garden Gate, you work directly with me – Mahrukh Tariq. I manage your property with the same standards I apply to my own 90-unit portfolio: honest pricing, rigorous tenant screening, and personal attention that corporations can't replicate.")),
                ('cta_text', models.CharField(default='Show Me How This Actually Works', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='LeadMagnetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Free 15 Minute Property<br>Assessment', max_length=200)),
                ('subtitle', models.CharField(default='No sales pitch. Just straight answers to:', max_length=200)),
                ('bullet_1', models.CharField(default='What your property should actually rent for', max_length=200)),
                ('bullet_2', models.CharField(default="Where you're currently losing money", max_length=200)),
                ('bullet_3', models.CharField(default="Whether we're a good fit (honest answer)", max_length=200)),
                ('description', models.TextField(default="If we're not right for you, I'll tell you. If we are, you'll know exactly what happens next.")),
                ('cta_text', models.CharField(default='Show Me How This Actually Works', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Magnet Section',
                'verbose_name_plural': 'Lead Magnet Section',
            },
        ),
        migrations.CreateModel(
            name='MethodologySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The Garden Gate Framework', max_length=200)),
                ('description', models.TextField(default='Most companies chase volume. We build relationships. Every property receives personalized attention, open communication, and proactive care.')),
                ('cta_text', models.CharField(default='See the Framework in Action', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Methodology Section',
                'verbose_name_plural': 'Methodology Section',
            },
        ),
        migrations.CreateModel(
            name='MethodologyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Step number (1-5)', unique=True)),
                ('title', models.CharField(help_text="Step title (e.g., 'Assessment')", max_length=100)),
                ('description', models.TextField(help_text='Step description')),
                ('result_text', models.CharField(help_text='Result text', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Methodology Step',
                'verbose_name_plural': 'Methodology Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='MissionVisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_subtitle', models.CharField(default="Deliver What Corporate Management Can't.", max_length=200)),
                ('mission_description', models.TextField(default='We exist because landlords deserve better — direct access, transparent pricing, and genuine partnership. Garden Gate gives you clarity, control, and confidence in your investment.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_subtitle', models.CharField(default='Boutique Management That Puts Landlords First.', max_length=200)),
                ('vision_description', models.TextField(default="We're building Northern Virginia's most trusted boutique property management firm — where landlords enjoy ownership, not endure it.")),
                ('cta_text', models.CharField(default='Join Us', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission/Vision Section',
                'verbose_name_plural': 'Mission/Vision Section',
            },
        ),
        migrations.CreateModel(
            name='PainPointsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Common Problems.<br>Clear Solutions.', max_length=200)),
                ('description', models.TextField(default="Owning rental property shouldn't mean chasing managers or worrying about surprise bills. But too often, landlords deal with:")),
                ('pain_point_1', models.CharField(default='Managers who disappear when you need answers.', max_length=200)),
                ('pain_point_2', models.CharField(default='Inflated maintenance costs and hidden markups.', max_length=200)),
                ('pain_point_3', models.CharField(default='Weak screening that lets in problem tenants.', max_length=200)),
                ('pain_point_4', models.CharField(default='Generic, one-size-fits-all service.', max_length=200)),
                ('pain_point_5', models.CharField(default='Unapproved expenses with zero transparency.', max_length=200)),
                ('solution_1', models.CharField(default='<strong class="text-gold italic">Immediate Access</strong> — You call. I answer. Same day.', max_length=300)),
                ('solution_2', models.CharField(default='<strong class="text-gold italic">Transparent Pricing</strong> — You review every estimate before work begins.', max_length=300)),
                ('solution_3', models.CharField(default='<strong class="text-gold italic">Rigorous Screening</strong> — Every tenant meets me personally before approval.', max_length=300)),
                ('solution_4', models.CharField(default='<strong class="text-gold italic">Customized Management</strong> — Your goals, your preferences, your plan.', max_length=300)),
                ('solution_5', models.CharField(default='<strong class="text-gold italic">Total Transparency</strong> — You\'re informed before money moves. Always.', max_length=300)),
                ('cta_text', models.CharField(default='Turn Frustrations Into Results', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pain Points Section',
                'verbose_name_plural': 'Pain Points Section',
            },
        ),
        migrations.CreateModel(
            name='StatisticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Quality Management Matters', max_length=200)),
                ('subtitle', models.CharField(default='The Cost of Poor Management:', max_length=200)),
                ('point_1', models.CharField(default='Long vacancies that cost thousands in lost rent.', max_length=300)),
                ('point_2', models.CharField(default='Vendor markups of 10–25% on maintenance invoices.', max_length=300)),
                ('point_3', models.CharField(default='Unresponsive managers — 29% of tenants report landlords are "slow to get things done."', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistics Section',
                'verbose_name_plural': 'Statistics Section',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_number', models.IntegerField(help_text='Testimonial number (1, 2, or 3)', unique=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Avatar image URL', null=True)),
                ('avatar_alt', models.CharField(blank=True, help_text='Avatar alt text', max_length=200)),
                ('quote_short', models.CharField(help_text='Short quote (italic)', max_length=300)),
                ('quote_long', models.TextField(help_text='Long quote/description')),
                ('author_name', models.CharField(help_text='Author name', max_length=100)),
                ('author_title', models.CharField(help_text='Author title/location', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['testimonial_number'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Landlords Stop Looking After Finding Us', max_length=200)),
                ('cta_text', models.CharField(default='See What We Can Do', max_length=100)),
                ('cta_link', models.CharField(default='#consultation', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
    ]
