# Generated by Django 5.1.2 on 2026-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_aboutsection_credibilitycard_credibilitysection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Short excerpt/preview text', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('featured_image_url', models.URLField(blank=True, help_text='Featured image URL', null=True)),
                ('featured_image_alt', models.CharField(blank=True, help_text='Featured image alt text', max_length=200)),
                ('author_name', models.CharField(default='Mahrukh Tariq', help_text='Author name', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Publication date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_published', models.BooleanField(default=True, help_text='Published status')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Insights & Expertise', max_length=200)),
                ('subtitle', models.CharField(default='Learn from our experience managing properties and building successful landlord relationships.', max_length=300)),
                ('cta_text', models.CharField(default='View All Posts', max_length=100)),
                ('cta_link', models.CharField(default='#blog', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Section',
            },
        ),
    ]
