# Generated by Django 5.1.2 on 2026-02-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_blogpost_blogsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.IntegerField(help_text='Package number (1 or 2)', unique=True)),
                ('title', models.CharField(help_text="Package title (e.g., 'Rental Condominium Up to 2 Bedrooms')", max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=10)),
                ('services', models.TextField(help_text='Services included (one per line)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Package',
                'verbose_name_plural': 'Pricing Packages',
                'ordering': ['package_number'],
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Packages & Rates', max_length=200)),
                ('subtitle', models.CharField(default='NO HIDDEN FEES, CLEAR PRICING, EXCEPTIONAL SERVICE.', max_length=300)),
                ('disclaimer', models.CharField(default='No hidden fees. Professional management you can count on.', max_length=300)),
                ('cta_text', models.CharField(default='Get Started Today', max_length=100)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Section',
                'verbose_name_plural': 'Pricing Section',
            },
        ),
    ]
