# Generated by Django 5.1.2 on 2026-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_pricingpackage_pricingsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painpointssection',
            name='cta_text',
            field=models.CharField(default='Get a Free Rental Analysis', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='cta_text',
            field=models.CharField(default='Request Management Pricing', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonialssection',
            name='cta_text',
            field=models.CharField(default="Find Out If We're the Right Fit", max_length=100),
        ),
    ]
